# This is a generated file. Not intended for manual editing.
services:
  web-api:
    build:
      context: "D:\\Trabalho\\SuperHeroes"
      dockerfile: "src/Web.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Web.Api.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "web.api:dev"
    ports: []
    volumes:
    - "C:\\Users\\Mauro\\.nuget\\packages:/home/app/.nuget/packages"
    - "D:\\Trabalho\\SuperHeroes\\src\\Web.Api:/app:rw"
    - "D:\\Trabalho\\SuperHeroes:/src:rw"
    working_dir: "/app"
